routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});


Auth::routes();

Route::get('home', 'HomeController@index')->name('home');

Route::resource('neighborhoods', 'NeighborhoodController');

Route::resource('houses', 'HouseController');

Route::resource('dwellers', 'DwellerController');

Route::resource('professions', 'ProfessionController');

resources/views/houses/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Casa
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'houses.store']) !!}

                        @include('houses.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        $(document).ready(function()
        {
            $('.select2').select2();
        });
    </script>
@endsection

resources/views/houses/datatables_actions.blade.php
{!! Form::open(['route' => ['houses.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('houses.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('houses.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/houses/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Casa
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($house, ['route' => ['houses.update', $house->id], 'method' => 'patch']) !!}

                        @include('houses.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/houses/fields.blade.php
<!-- Street Field -->
<div class="form-group col-sm-6">
    {!! Form::label('street', 'Rua:') !!}
    {!! Form::text('street', null, ['class' => 'form-control']) !!}
</div>

<!-- Number Field -->
<div class="form-group col-sm-2">
    {!! Form::label('number', 'Numero:') !!}
    {!! Form::number('number', null, ['class' => 'form-control']) !!}
</div>

<!-- Neighborhood Id Field -->
<div class="form-group col-sm-4">
    {!! Form::label('neighborhood_id', 'Bairro:') !!}
    {!! Form::select('neighborhood_id', ['' => 'Selecione...'] + $neighborhoods, null,['class' => 'form-control select2']) !!}
</div>

<div id="dwellers" class="form-group col-sm-12">
    <h4 style="margin: 40px 0 20px 0">
        Moradores:
    </h4>

    <div class="row">
        <div class="form-group col-sm-9">
            {!! Form::label('name', 'Nome:') !!}
            {!! Form::text('dwellers[name][]', null, ['class' => 'form-control']) !!}
        </div>

        <div class="form-group col-sm-2">
            {!! Form::label('age', 'Idade:') !!}
            {!! Form::number('dwellers[age][]', null, ['class' => 'form-control']) !!}
        </div>

        <div class="form-group col-sm-1 btnPlus" style="margin-top: 24px">
            {!! Form::button('+', ['class' => 'btn btn-success']) !!}
        </div>
    </div>

</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Salvar', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('houses.index') !!}" class="btn btn-default">Cancelar</a>
</div>

@section('scripts')

<script>
    function addDweller()
    {
        $('#dwellers').append(`<div class="row">
            <div class="form-group col-sm-9">
                {!! Form::label('name', 'Nome:') !!}
                {!! Form::text('dwellers[name][]', null, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group col-sm-2">
                {!! Form::label('age', 'Idade:') !!}
                {!! Form::number('dwellers[age][]', null, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group btnPlus col-sm-1" style="margin-top: 24px">
                {!! Form::button('+', ['class' => 'btn btn-success']) !!}
            </div>
        </div>`);
    }

    $('#dwellers').on('click','.btnPlus', addDweller);
</script>

@endsection

resources/views/houses/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Casas</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('houses.create') !!}">Cadastrar</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('houses.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/houses/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Casa
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('houses.show_fields')
                    <a href="{!! route('houses.index') !!}" class="btn btn-default">Voltar</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/houses/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $house->id !!}</p>
</div>

<!-- Street Field -->
<div class="form-group">
    {!! Form::label('street', 'Rua:') !!}
    <p>{!! $house->street !!}</p>
</div>

<!-- Number Field -->
<div class="form-group">
    {!! Form::label('number', 'Numero:') !!}
    <p>{!! $house->number !!}</p>
</div>

<!-- Neighborhood Id Field -->
<div class="form-group">
    {!! Form::label('neighborhood_id', 'Bairro:') !!}
    <p>{!! $house->neighborhood->name !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Criado em:') !!}
    <p>{!! date_format($house->created_at,'d/m/Y H:i') !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Atualizado em:') !!}
    <p>{!! date_format($house->updated_at,'d/m/Y H:i') !!}</p>
</div>

resources/views/houses/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection